spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/employee_db
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update